from . import student
from . import crm_lead
from . import student_form_link
from . import welcome_mail
from . import product
from . import discount
from . import branch
from . import semester_details
from . import batch
from . import admission_report_wizard
